# Configuration for cargo-deny
# https://github.com/EmbarkStudios/cargo-deny

[advisories]
# Use version 2 for stricter defaults
version = 2
# Allow unmaintained crates in dependencies but not in workspace
unmaintained = "transitive"
yanked = "warn"

[licenses]
# Use version 2 for stricter defaults
version = 2
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
]

[[licenses.exceptions]]
# Ring uses a custom license but is widely trusted
name = "ring"
allow = ["ISC", "MIT", "OpenSSL"]

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# Skip certain crates that commonly have multiple versions
skip = [
    { name = "windows-sys" },
]

[sources]
# Deny crates from unknown registries
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]