# Configuration for release-plz
# https://release-plz.ieni.dev/docs/config

[workspace]
# Enable changelog generation
changelog_update = true

# Enable git releases and tags
git_release_enable = true
git_tag_enable = true
pr_branch_prefix = "automated/release-plz/"

# PR settings
pr_labels = ["release", "automated"]
pr_draft = false
pr_name = "chore: release version {{version}}"

# Publishing
publish = true

# GitHub release body template
# Note: Use per-release changelog (like PR body) since top-level
# `changelog` may be empty for GitHub releases.
git_release_body = """
{%- for release in releases -%}
## 📦 {{ release.package }} {{ release.previous_version }} → {{ release.next_version }}

### 🔗 Compare Changes
[**View all changes since v{{ release.previous_version }}**](https://github.com/genai-rs/openai-client-base/compare/v{{ release.previous_version }}...v{{ release.next_version }})

{%- if release.changelog %}

### 📋 Changelog

{{ release.changelog }}
{%- else %}

_No changelog available for this release_
{%- endif %}

{%- endfor %}
"""

# PR body template  
pr_body = """
{%- for release in releases -%}
## 📦 {{ release.package }} {{ release.previous_version }} → {{ release.next_version }}

### 🔗 Compare Changes
[**View all changes since v{{ release.previous_version }}**](https://github.com/genai-rs/openai-client-base/compare/v{{ release.previous_version }}...HEAD)

{%- if release.changelog %}

### 📋 Changelog

{{ release.changelog }}
{%- else %}

_No changelog available for this release_
{%- endif %}

{%- endfor %}

---
_This PR was generated by [release-plz](https://github.com/MarcoIeni/release-plz/)_
"""
