#!/usr/bin/env python3
"""
Fix enum variant references to simplified types across all generated models.

This is a generic solution for the problem where:
1. The spec patching process simplifies certain schemas to simple string types
2. The OpenAPI generator creates enums with variants referencing those types
3. This causes compilation errors because the types no longer exist as structs

This script:
- Automatically detects simplified schemas from the patched OpenAPI spec
- Scans all generated model files for enum variants referencing these types
- Removes invalid variants and their associated impl blocks

No manual configuration needed - it discovers simplified types at runtime.
"""

import re
import sys
from pathlib import Path
from typing import Set

ROOT = Path(__file__).parent.parent
MODELS = ROOT / 'src' / 'models'


def load_simplified_schemas_from_tracking_file(tracking_file: Path) -> Set[str]:
    """
    Load the list of simplified schemas from the tracking file.

    The tracking file is generated by fix_model_fields.py and contains
    one schema name per line.
    """
    if not tracking_file.exists():
        return set()

    with open(tracking_file, 'r') as f:
        schemas = {line.strip() for line in f if line.strip()}

    return schemas


def fix_enum_variants_in_file(file_path: Path, simplified_types: Set[str]) -> bool:
    """
    Fix enum variants in a single file that reference simplified types.

    Returns True if changes were made.
    """
    content = file_path.read_text()
    original_content = content
    changes_made = False

    # Build pattern for any of the simplified types
    # Match variants like: Variantname(models::SimplifiedType),
    for type_name in simplified_types:
        pattern = rf'^\s*([A-Z][a-z0-9_]*)\(models::{type_name}\),?\s*$'

        if re.search(pattern, content, re.MULTILINE):
            print(f"  Found variant referencing simplified type {type_name}")
            content = re.sub(pattern, '', content, flags=re.MULTILINE)
            changes_made = True

            # Also remove associated helper functions
            # Pattern: pub fn variant_name(...) -> Self { Self::VariantName(...) }
            variant_fn_pattern = rf'pub\s+fn\s+[a-z][a-z0-9_]*\([^)]*\)\s*->\s*Self\s*\{{[^}}]*Self::[A-Z][a-z0-9_]*\(models::{type_name}\([^)]*\)\)[^}}]*\}}'
            content = re.sub(variant_fn_pattern, '', content, flags=re.DOTALL)

    # Clean up excessive empty lines
    if changes_made:
        content = re.sub(r'\n\s*\n\s*\n', '\n\n', content)

        if content != original_content:
            file_path.write_text(content)
            return True

    return False


def scan_and_fix_all_models(simplified_types: Set[str]) -> int:
    """
    Scan all model files and fix enum variants referencing simplified types.

    Returns the number of files fixed.
    """
    if not MODELS.exists():
        print(f"Models directory not found: {MODELS}")
        return 0

    files_fixed = 0

    for model_file in MODELS.glob('*.rs'):
        if model_file.name == 'mod.rs':
            continue

        if fix_enum_variants_in_file(model_file, simplified_types):
            print(f"✓ Fixed {model_file.name}")
            files_fixed += 1

    return files_fixed


def main():
    print("Generic fix for enum variants referencing simplified types")
    print("=" * 60)

    # Load simplified schemas from tracking file generated by fix_model_fields.py
    tracking_file = ROOT / 'target' / 'reports' / 'simplified_schemas.txt'

    print(f"\n1. Loading simplified schemas from tracking file...")
    print(f"   Path: {tracking_file}")

    simplified_types = load_simplified_schemas_from_tracking_file(tracking_file)

    if not simplified_types:
        print(f"   ⚠️  Tracking file not found or empty: {tracking_file}")
        print("   This script needs the tracking file generated by fix_model_fields.py")
        print("   Skipping enum variant fixes.")
        return
    else:
        print(f"   Found {len(simplified_types)} simplified schemas:")
        for schema in sorted(simplified_types):
            print(f"     - {schema}")

    # Step 2: Scan and fix all model files
    print("\n2. Scanning and fixing model files...")
    files_fixed = scan_and_fix_all_models(simplified_types)

    print("\n" + "=" * 60)
    if files_fixed > 0:
        print(f"✅ Fixed {files_fixed} file(s)")
    else:
        print("✅ No fixes needed - all enum variants are valid")


if __name__ == "__main__":
    main()
