/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentToolConfigParamComputerUse : Browser use in an OpenAI-hosted session.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct AgentToolConfigParamComputerUse {
    /// The type of the object. Always `computer_use`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Whether computer tool outputs include screenshots. Defaults to `false`.
    #[serde(
        rename = "include_screenshots",
        skip_serializing_if = "Option::is_none"
    )]
    pub include_screenshots: Option<bool>,
}

impl AgentToolConfigParamComputerUse {
    /// Browser use in an OpenAI-hosted session.
    pub fn new(r#type: Type) -> AgentToolConfigParamComputerUse {
        AgentToolConfigParamComputerUse {
            r#type,
            include_screenshots: None,
        }
    }
}
/// The type of the object. Always `computer_use`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "computer_use")]
    ComputerUse,
}

impl Default for Type {
    fn default() -> Type {
        Self::ComputerUse
    }
}

impl std::fmt::Display for AgentToolConfigParamComputerUse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
