/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentToolResourceComputerUse : Browser use in an OpenAI-hosted session.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct AgentToolResourceComputerUse {
    /// The type of the object. Always `computer_use`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Whether computer tool outputs include screenshots.
    #[serde(rename = "include_screenshots")]
    pub include_screenshots: bool,
}

impl AgentToolResourceComputerUse {
    /// Browser use in an OpenAI-hosted session.
    pub fn new(r#type: Type, include_screenshots: bool) -> AgentToolResourceComputerUse {
        AgentToolResourceComputerUse {
            r#type,
            include_screenshots,
        }
    }
}
/// The type of the object. Always `computer_use`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "computer_use")]
    ComputerUse,
}

impl Default for Type {
    fn default() -> Type {
        Self::ComputerUse
    }
}

impl std::fmt::Display for AgentToolResourceComputerUse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
