/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnswerResource : A completed question always includes its name, including null when unnamed.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AnswerResource {
    Predicate(Box<models::AnswerResourcePredicate>),
    Choice(Box<models::AnswerResourceChoice>),
    Score(Box<models::AnswerResourceScore>),
    Refusal(Box<models::AnswerResourceRefusal>),
}

impl Default for AnswerResource {
    fn default() -> Self {
        Self::Predicate(Default::default())
    }
}
