/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApplyPatchUpdateFileOperation : Instruction describing how to update a file via the apply_patch tool.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ApplyPatchUpdateFileOperation {
    /// Update an existing file with the provided diff.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Path of the file to update.
    #[serde(rename = "path")]
    pub path: String,
    /// Diff to apply.
    #[serde(rename = "diff")]
    pub diff: String,
}

impl ApplyPatchUpdateFileOperation {
    /// Instruction describing how to update a file via the apply_patch tool.
    pub fn new(r#type: Type, path: String, diff: String) -> ApplyPatchUpdateFileOperation {
        ApplyPatchUpdateFileOperation { r#type, path, diff }
    }
}
/// Update an existing file with the provided diff.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "update_file")]
    UpdateFile,
}

impl Default for Type {
    fn default() -> Type {
        Self::UpdateFile
    }
}

impl std::fmt::Display for ApplyPatchUpdateFileOperation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
