/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogApiKeyUpdatedChangesRequested : The payload used to update the API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct AuditLogApiKeyUpdatedChangesRequested {
    /// A list of scopes allowed for the API key, e.g. `[\"api.model.request\"]`
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
}

impl AuditLogApiKeyUpdatedChangesRequested {
    /// The payload used to update the API key.
    pub fn new() -> AuditLogApiKeyUpdatedChangesRequested {
        AuditLogApiKeyUpdatedChangesRequested {
            scopes: None,
        }
    }
}



impl std::fmt::Display for AuditLogApiKeyUpdatedChangesRequested {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
