/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutomaticThreadTitlingParam : Controls whether ChatKit automatically generates thread titles.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct AutomaticThreadTitlingParam {
    /// Enable automatic thread title generation. Defaults to true.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl AutomaticThreadTitlingParam {
    /// Controls whether ChatKit automatically generates thread titles.
    pub fn new() -> AutomaticThreadTitlingParam {
        AutomaticThreadTitlingParam { enabled: None }
    }
}

impl std::fmt::Display for AutomaticThreadTitlingParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
