/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaResponseConfigurationUpdateItemParamReasoning : Updates to reasoning configuration. Only effort is supported.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaResponseConfigurationUpdateItemParamReasoning {
    #[serde(
        rename = "effort",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effort: Option<Option<models::BetaReasoningEffort>>,
}

impl BetaResponseConfigurationUpdateItemParamReasoning {
    /// Updates to reasoning configuration. Only effort is supported.
    pub fn new() -> BetaResponseConfigurationUpdateItemParamReasoning {
        BetaResponseConfigurationUpdateItemParamReasoning { effort: None }
    }
}

impl std::fmt::Display for BetaResponseConfigurationUpdateItemParamReasoning {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
