/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaResponseAudioTranscriptDoneEvent : Emitted when the full audio transcript is completed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaResponseAudioTranscriptDoneEvent {
    #[serde(
        rename = "agent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub agent: Option<Option<Box<models::BetaAgentTag>>>,
    /// The type of the event. Always `response.audio.transcript.done`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The sequence number of this event.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
}

impl BetaResponseAudioTranscriptDoneEvent {
    /// Emitted when the full audio transcript is completed.
    pub fn new(r#type: Type, sequence_number: i32) -> BetaResponseAudioTranscriptDoneEvent {
        BetaResponseAudioTranscriptDoneEvent {
            agent: None,
            r#type,
            sequence_number,
        }
    }
}
/// The type of the event. Always `response.audio.transcript.done`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.audio.transcript.done")]
    ResponseAudioTranscriptDone,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseAudioTranscriptDone
    }
}

impl std::fmt::Display for BetaResponseAudioTranscriptDoneEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
