/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaResponseIncompleteEvent : An event that is emitted when a response finishes as incomplete.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaResponseIncompleteEvent {
    #[serde(
        rename = "agent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub agent: Option<Option<Box<models::BetaAgentTag>>>,
    /// The type of the event. Always `response.incomplete`.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "response")]
    pub response: Box<models::BetaResponse>,
    /// The sequence number of this event.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
}

impl BetaResponseIncompleteEvent {
    /// An event that is emitted when a response finishes as incomplete.
    pub fn new(
        r#type: Type,
        response: models::BetaResponse,
        sequence_number: i32,
    ) -> BetaResponseIncompleteEvent {
        BetaResponseIncompleteEvent {
            agent: None,
            r#type,
            response: Box::new(response),
            sequence_number,
        }
    }
}
/// The type of the event. Always `response.incomplete`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.incomplete")]
    ResponseIncomplete,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseIncomplete
    }
}

impl std::fmt::Display for BetaResponseIncompleteEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
