/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaOutputTextContent : A text output from the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaOutputTextContent {
    /// The type of the output text. Always `output_text`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The text output from the model.
    #[serde(rename = "text")]
    pub text: String,
    /// The annotations of the text output.
    #[serde(rename = "annotations")]
    pub annotations: Vec<models::BetaAnnotation>,
    #[serde(rename = "logprobs")]
    pub logprobs: Vec<models::BetaLogProb>,
}

impl BetaOutputTextContent {
    /// A text output from the model.
    pub fn new(
        r#type: Type,
        text: String,
        annotations: Vec<models::BetaAnnotation>,
        logprobs: Vec<models::BetaLogProb>,
    ) -> BetaOutputTextContent {
        BetaOutputTextContent {
            r#type,
            text,
            annotations,
            logprobs,
        }
    }
}
/// The type of the output text. Always `output_text`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "output_text")]
    OutputText,
}

impl Default for Type {
    fn default() -> Type {
        Self::OutputText
    }
}

impl std::fmt::Display for BetaOutputTextContent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
