/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BetaResponseStreamEvent {
    BetaResponseAudioDeltaEvent(Box<models::BetaResponseAudioDeltaEvent>),
    BetaResponseAudioDoneEvent(Box<models::BetaResponseAudioDoneEvent>),
    BetaResponseAudioTranscriptDeltaEvent(Box<models::BetaResponseAudioTranscriptDeltaEvent>),
    BetaResponseAudioTranscriptDoneEvent(Box<models::BetaResponseAudioTranscriptDoneEvent>),
    BetaResponseCodeInterpreterCallCodeDeltaEvent(
        Box<models::BetaResponseCodeInterpreterCallCodeDeltaEvent>,
    ),
    BetaResponseCodeInterpreterCallCodeDoneEvent(
        Box<models::BetaResponseCodeInterpreterCallCodeDoneEvent>,
    ),
    BetaResponseCodeInterpreterCallCompletedEvent(
        Box<models::BetaResponseCodeInterpreterCallCompletedEvent>,
    ),
    BetaResponseCodeInterpreterCallInProgressEvent(
        Box<models::BetaResponseCodeInterpreterCallInProgressEvent>,
    ),
    BetaResponseCodeInterpreterCallInterpretingEvent(
        Box<models::BetaResponseCodeInterpreterCallInterpretingEvent>,
    ),
    BetaResponseCompletedEvent(Box<models::BetaResponseCompletedEvent>),
    BetaResponseContentPartAddedEvent(Box<models::BetaResponseContentPartAddedEvent>),
    BetaResponseContentPartDoneEvent(Box<models::BetaResponseContentPartDoneEvent>),
    BetaResponseCreatedEvent(Box<models::BetaResponseCreatedEvent>),
    BetaResponseErrorEvent(Box<models::BetaResponseErrorEvent>),
    BetaResponseFileSearchCallCompletedEvent(Box<models::BetaResponseFileSearchCallCompletedEvent>),
    BetaResponseFileSearchCallInProgressEvent(
        Box<models::BetaResponseFileSearchCallInProgressEvent>,
    ),
    BetaResponseFileSearchCallSearchingEvent(Box<models::BetaResponseFileSearchCallSearchingEvent>),
    BetaResponseFunctionCallArgumentsDeltaEvent(
        Box<models::BetaResponseFunctionCallArgumentsDeltaEvent>,
    ),
    BetaResponseFunctionCallArgumentsDoneEvent(
        Box<models::BetaResponseFunctionCallArgumentsDoneEvent>,
    ),
    BetaResponseInProgressEvent(Box<models::BetaResponseInProgressEvent>),
    BetaResponseFailedEvent(Box<models::BetaResponseFailedEvent>),
    BetaResponseIncompleteEvent(Box<models::BetaResponseIncompleteEvent>),
    BetaResponseOutputItemAddedEvent(Box<models::BetaResponseOutputItemAddedEvent>),
    BetaResponseOutputItemDoneEvent(Box<models::BetaResponseOutputItemDoneEvent>),
    BetaResponseReasoningSummaryPartAddedEvent(
        Box<models::BetaResponseReasoningSummaryPartAddedEvent>,
    ),
    BetaResponseReasoningSummaryPartDoneEvent(
        Box<models::BetaResponseReasoningSummaryPartDoneEvent>,
    ),
    BetaResponseReasoningSummaryTextDeltaEvent(
        Box<models::BetaResponseReasoningSummaryTextDeltaEvent>,
    ),
    BetaResponseReasoningSummaryTextDoneEvent(
        Box<models::BetaResponseReasoningSummaryTextDoneEvent>,
    ),
    BetaResponseReasoningTextDeltaEvent(Box<models::BetaResponseReasoningTextDeltaEvent>),
    BetaResponseReasoningTextDoneEvent(Box<models::BetaResponseReasoningTextDoneEvent>),
    BetaResponseRefusalDeltaEvent(Box<models::BetaResponseRefusalDeltaEvent>),
    BetaResponseRefusalDoneEvent(Box<models::BetaResponseRefusalDoneEvent>),
    BetaResponseTextDeltaEvent(Box<models::BetaResponseTextDeltaEvent>),
    BetaResponseTextDoneEvent(Box<models::BetaResponseTextDoneEvent>),
    BetaResponseWebSearchCallCompletedEvent(Box<models::BetaResponseWebSearchCallCompletedEvent>),
    BetaResponseWebSearchCallInProgressEvent(Box<models::BetaResponseWebSearchCallInProgressEvent>),
    BetaResponseWebSearchCallSearchingEvent(Box<models::BetaResponseWebSearchCallSearchingEvent>),
    BetaResponseImageGenCallCompletedEvent(Box<models::BetaResponseImageGenCallCompletedEvent>),
    BetaResponseImageGenCallGeneratingEvent(Box<models::BetaResponseImageGenCallGeneratingEvent>),
    BetaResponseImageGenCallInProgressEvent(Box<models::BetaResponseImageGenCallInProgressEvent>),
    BetaResponseImageGenCallPartialImageEvent(
        Box<models::BetaResponseImageGenCallPartialImageEvent>,
    ),
    BetaResponseMcpCallArgumentsDeltaEvent(Box<models::BetaResponseMcpCallArgumentsDeltaEvent>),
    BetaResponseMcpCallArgumentsDoneEvent(Box<models::BetaResponseMcpCallArgumentsDoneEvent>),
    BetaResponseMcpCallCompletedEvent(Box<models::BetaResponseMcpCallCompletedEvent>),
    BetaResponseMcpCallFailedEvent(Box<models::BetaResponseMcpCallFailedEvent>),
    BetaResponseMcpCallInProgressEvent(Box<models::BetaResponseMcpCallInProgressEvent>),
    BetaResponseMcpListToolsCompletedEvent(Box<models::BetaResponseMcpListToolsCompletedEvent>),
    BetaResponseMcpListToolsFailedEvent(Box<models::BetaResponseMcpListToolsFailedEvent>),
    BetaResponseMcpListToolsInProgressEvent(Box<models::BetaResponseMcpListToolsInProgressEvent>),
    BetaResponseOutputTextAnnotationAddedEvent(
        Box<models::BetaResponseOutputTextAnnotationAddedEvent>,
    ),
    BetaResponseQueuedEvent(Box<models::BetaResponseQueuedEvent>),
    BetaResponseCustomToolCallInputDeltaEvent(
        Box<models::BetaResponseCustomToolCallInputDeltaEvent>,
    ),
    BetaResponseCustomToolCallInputDoneEvent(Box<models::BetaResponseCustomToolCallInputDoneEvent>),
}

/// The completion status of the summary part. Omitted when the part completed normally and set to `incomplete` when generation was interrupted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    Incomplete,
}
