/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaFunctionShellCallOutputContentParam : Captured stdout and stderr for a portion of a shell tool call output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaFunctionShellCallOutputContentParam {
    /// Captured stdout output for the shell call.
    #[serde(rename = "stdout")]
    pub stdout: String,
    /// Captured stderr output for the shell call.
    #[serde(rename = "stderr")]
    pub stderr: String,
    #[serde(rename = "outcome")]
    pub outcome: Box<models::BetaFunctionShellCallOutputOutcomeParam>,
}

impl BetaFunctionShellCallOutputContentParam {
    /// Captured stdout and stderr for a portion of a shell tool call output.
    pub fn new(
        stdout: String,
        stderr: String,
        outcome: models::BetaFunctionShellCallOutputOutcomeParam,
    ) -> BetaFunctionShellCallOutputContentParam {
        BetaFunctionShellCallOutputContentParam {
            stdout,
            stderr,
            outcome: Box::new(outcome),
        }
    }
}

impl std::fmt::Display for BetaFunctionShellCallOutputContentParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
