/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaResponseCodeInterpreterCallWsInterpreting : Emitted when the code interpreter is actively interpreting the code snippet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaResponseCodeInterpreterCallWsInterpreting {
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Box<models::BetaAgentTag>>,
    /// The type of the event. Always `response.code_interpreter_call.interpreting`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The index of the output item in the response for which the code interpreter is interpreting code.
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The unique identifier of the code interpreter tool call item.
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The sequence number of this event, used to order streaming events.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
    /// The WebSocket lane that emitted this event. This field is present when the originating `response.create` event supplied a `stream_id`.
    #[serde(rename = "stream_id", skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<String>,
}

impl BetaResponseCodeInterpreterCallWsInterpreting {
    /// Emitted when the code interpreter is actively interpreting the code snippet.
    pub fn new(
        r#type: Type,
        output_index: i32,
        item_id: String,
        sequence_number: i32,
    ) -> BetaResponseCodeInterpreterCallWsInterpreting {
        BetaResponseCodeInterpreterCallWsInterpreting {
            agent: None,
            r#type,
            output_index,
            item_id,
            sequence_number,
            stream_id: None,
        }
    }
}
/// The type of the event. Always `response.code_interpreter_call.interpreting`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.code_interpreter_call.interpreting")]
    ResponseCodeInterpreterCallInterpreting,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseCodeInterpreterCallInterpreting
    }
}

impl std::fmt::Display for BetaResponseCodeInterpreterCallWsInterpreting {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
