/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaAgentMessage {
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Box<models::BetaAgentTag>>,
    /// The type of the item. Always `agent_message`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The unique ID of the agent message.
    #[serde(rename = "id")]
    pub id: String,
    /// The sending agent identity.
    #[serde(rename = "author")]
    pub author: String,
    /// The destination agent identity.
    #[serde(rename = "recipient")]
    pub recipient: String,
    /// Encrypted content sent between agents.
    #[serde(rename = "content")]
    pub content: Vec<models::BetaAgentMessageContentInner>,
}

impl BetaAgentMessage {
    pub fn new(
        r#type: Type,
        id: String,
        author: String,
        recipient: String,
        content: Vec<models::BetaAgentMessageContentInner>,
    ) -> BetaAgentMessage {
        BetaAgentMessage {
            agent: None,
            r#type,
            id,
            author,
            recipient,
            content,
        }
    }
}
/// The type of the item. Always `agent_message`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "agent_message")]
    AgentMessage,
}

impl Default for Type {
    fn default() -> Type {
        Self::AgentMessage
    }
}

impl std::fmt::Display for BetaAgentMessage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
