/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaAccessProgramsParam : Domain-specific access programs to use for this request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaAccessProgramsParam {
    #[serde(rename = "cyber", skip_serializing_if = "Option::is_none")]
    pub cyber: Option<models::BetaCyberAccessProgramEnum>,
}

impl BetaAccessProgramsParam {
    /// Domain-specific access programs to use for this request.
    pub fn new() -> BetaAccessProgramsParam {
        BetaAccessProgramsParam { cyber: None }
    }
}

impl std::fmt::Display for BetaAccessProgramsParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
