/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaResponseMcpListToolsFailedEvent : Emitted when the attempt to list available MCP tools has failed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct BetaResponseMcpListToolsFailedEvent {
    #[serde(
        rename = "agent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub agent: Option<Option<Box<models::BetaAgentTag>>>,
    /// The type of the event. Always 'response.mcp_list_tools.failed'.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the MCP tool call item that failed.
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The index of the output item that failed.
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The sequence number of this event.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
}

impl BetaResponseMcpListToolsFailedEvent {
    /// Emitted when the attempt to list available MCP tools has failed.
    pub fn new(
        r#type: Type,
        item_id: String,
        output_index: i32,
        sequence_number: i32,
    ) -> BetaResponseMcpListToolsFailedEvent {
        BetaResponseMcpListToolsFailedEvent {
            agent: None,
            r#type,
            item_id,
            output_index,
            sequence_number,
        }
    }
}
/// The type of the event. Always 'response.mcp_list_tools.failed'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.mcp_list_tools.failed")]
    ResponseMcpListToolsFailed,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseMcpListToolsFailed
    }
}

impl std::fmt::Display for BetaResponseMcpListToolsFailedEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
