/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionMessageCustomToolCall : A call to a custom tool created by the model. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ChatCompletionMessageCustomToolCall {
    /// The ID of the tool call.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the tool. Always `custom`.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "custom")]
    pub custom: Box<models::ChatCompletionMessageCustomToolCallCustom>,
}

impl ChatCompletionMessageCustomToolCall {
    /// A call to a custom tool created by the model. 
    pub fn new(id: String, r#type: Type, custom: models::ChatCompletionMessageCustomToolCallCustom) -> ChatCompletionMessageCustomToolCall {
        ChatCompletionMessageCustomToolCall {
            id,
            r#type,
            custom: Box::new(custom),
        }
    }
}
/// The type of the tool. Always `custom`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Custom
    }
}



impl std::fmt::Display for ChatCompletionMessageCustomToolCall {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
