/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ComputerUseApprovalRequestKindResource {
    BrowserAuthentication(Box<models::ComputerUseApprovalRequestKindResourceBrowserAuthentication>),
    BrowserOriginAccess(Box<models::ComputerUseApprovalRequestKindResourceBrowserOriginAccess>),
}

impl Default for ComputerUseApprovalRequestKindResource {
    fn default() -> Self {
        Self::BrowserAuthentication(Default::default())
    }
}
