/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ComputerScreenshotResource : A browser screenshot emitted by the model during computer use.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ComputerScreenshotResource {
    /// The content type. Always `computer_screenshot`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The complete JPEG image as a base64 data URL.
    #[serde(rename = "image_url")]
    pub image_url: String,
}

impl ComputerScreenshotResource {
    /// A browser screenshot emitted by the model during computer use.
    pub fn new(r#type: Type, image_url: String) -> ComputerScreenshotResource {
        ComputerScreenshotResource { r#type, image_url }
    }
}
/// The content type. Always `computer_screenshot`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "computer_screenshot")]
    ComputerScreenshot,
}

impl Default for Type {
    fn default() -> Type {
        Self::ComputerScreenshot
    }
}

impl std::fmt::Display for ComputerScreenshotResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
