/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompactionBody : A compaction item generated by the [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct CompactionBody {
    /// The type of the item. Always `compaction`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The unique ID of the compaction item.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "encrypted_content")]
    pub encrypted_content: String,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl CompactionBody {
    /// A compaction item generated by the [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
    pub fn new(r#type: Type, id: String, encrypted_content: String) -> CompactionBody {
        CompactionBody {
            r#type,
            id,
            encrypted_content,
            created_by: None,
        }
    }
}
/// The type of the item. Always `compaction`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "compaction")]
    Compaction,
}

impl Default for Type {
    fn default() -> Type {
        Self::Compaction
    }
}

impl std::fmt::Display for CompactionBody {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
