/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "action")]
pub enum ComputerUseApprovalResponseKindResource {
    #[serde(rename = "submit")]
    BrowserAuthenticationSubmitResource(
        Box<models::ComputerUseApprovalResponseKindResourceBrowserAuthenticationSubmitResource>,
    ),
    #[serde(rename = "cancel")]
    BrowserAuthenticationCancelResource(
        Box<models::ComputerUseApprovalResponseKindResourceBrowserAuthenticationCancelResource>,
    ),
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "browser_authentication")]
    BrowserAuthentication,
}

impl Default for Type {
    fn default() -> Type {
        Self::BrowserAuthentication
    }
}
