/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ContainerFileListResource {
    #[serde(rename = "object", deserialize_with = "Option::deserialize")]
    pub object: Option<serde_json::Value>,
    /// A list of container files.
    #[serde(rename = "data")]
    pub data: Vec<models::ContainerFileResource>,
    /// The ID of the first file in the list.
    #[serde(rename = "first_id")]
    pub first_id: String,
    /// The ID of the last file in the list.
    #[serde(rename = "last_id")]
    pub last_id: String,
    /// Whether there are more files available.
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl ContainerFileListResource {
    pub fn new(
        object: Option<serde_json::Value>,
        data: Vec<models::ContainerFileResource>,
        first_id: String,
        last_id: String,
        has_more: bool,
    ) -> ContainerFileListResource {
        ContainerFileListResource {
            object,
            data,
            first_id,
            last_id,
            has_more,
        }
    }
}

impl std::fmt::Display for ContainerFileListResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
