/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ContainerNetworkPolicyDomainSecretParam {
    /// The domain associated with the secret.
    #[serde(rename = "domain")]
    pub domain: String,
    /// The name of the secret to inject for the domain.
    #[serde(rename = "name")]
    pub name: String,
    /// The secret value to inject for the domain.
    #[serde(rename = "value")]
    pub value: String,
}

impl ContainerNetworkPolicyDomainSecretParam {
    pub fn new(
        domain: String,
        name: String,
        value: String,
    ) -> ContainerNetworkPolicyDomainSecretParam {
        ContainerNetworkPolicyDomainSecretParam {
            domain,
            name,
            value,
        }
    }
}

impl std::fmt::Display for ContainerNetworkPolicyDomainSecretParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
