/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContainerAutoParamSkillsInner {
    SkillReferenceParam(Box<models::SkillReferenceParam>),
    InlineSkillParam(Box<models::InlineSkillParam>),
}

impl Default for ContainerAutoParamSkillsInner {
    fn default() -> Self {
        Self::SkillReferenceParam(Default::default())
    }
}
