/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct CreateThreadAndRunRequestToolResourcesCodeInterpreter {
    /// A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a maximum of 20 files associated with the tool. 
    #[serde(rename = "file_ids", skip_serializing_if = "Option::is_none")]
    pub file_ids: Option<Vec<String>>,
}

impl CreateThreadAndRunRequestToolResourcesCodeInterpreter {
    pub fn new() -> CreateThreadAndRunRequestToolResourcesCodeInterpreter {
        CreateThreadAndRunRequestToolResourcesCodeInterpreter {
            file_ids: None,
        }
    }
}



impl std::fmt::Display for CreateThreadAndRunRequestToolResourcesCodeInterpreter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
