/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateThreadRequestToolResourcesAnyOfFileSearchVectorStoresInnerChunkingStrategy : The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CreateThreadRequestToolResourcesAnyOfFileSearchVectorStoresInnerChunkingStrategy {}
