/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct CustomToolCallResource {
    /// The type of the custom tool call. Always `custom_tool_call`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The unique ID of the custom tool call item.
    #[serde(rename = "id")]
    pub id: String,
    /// An identifier used to map this custom tool call to a tool call output.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The namespace of the custom tool being called.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The name of the custom tool being called.
    #[serde(rename = "name")]
    pub name: String,
    /// The input for the custom tool call generated by the model.
    #[serde(rename = "input")]
    pub input: String,
    #[serde(rename = "status")]
    pub status: models::FunctionCallStatus,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl CustomToolCallResource {
    pub fn new(
        r#type: Type,
        id: String,
        call_id: String,
        name: String,
        input: String,
        status: models::FunctionCallStatus,
    ) -> CustomToolCallResource {
        CustomToolCallResource {
            r#type,
            id,
            call_id,
            namespace: None,
            name,
            input,
            status,
            created_by: None,
        }
    }
}
/// The type of the custom tool call. Always `custom_tool_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom_tool_call")]
    CustomToolCall,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomToolCall
    }
}

impl std::fmt::Display for CustomToolCallResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
