/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DecisionsUsageGroupBy {
    #[serde(rename = "project_id")]
    ProjectId,
    #[serde(rename = "user_id")]
    UserId,
    #[serde(rename = "api_key_id")]
    ApiKeyId,
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "service_tier")]
    ServiceTier,
    #[serde(rename = "api_source")]
    ApiSource,
}

impl std::fmt::Display for DecisionsUsageGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ProjectId => write!(f, "project_id"),
            Self::UserId => write!(f, "user_id"),
            Self::ApiKeyId => write!(f, "api_key_id"),
            Self::Model => write!(f, "model"),
            Self::Batch => write!(f, "batch"),
            Self::ServiceTier => write!(f, "service_tier"),
            Self::ApiSource => write!(f, "api_source"),
        }
    }
}

impl Default for DecisionsUsageGroupBy {
    fn default() -> DecisionsUsageGroupBy {
        Self::ProjectId
    }
}
