/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeletedSessionArtifactResource : Confirmation that an immutable session artifact was deleted.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct DeletedSessionArtifactResource {
    /// The ID of the deleted session artifact.
    #[serde(rename = "id")]
    pub id: String,
    /// The object type. Always `agent.session.artifact.deleted`.
    #[serde(rename = "object")]
    pub object: Object,
    /// Whether the session artifact was deleted. Always `true`.
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl DeletedSessionArtifactResource {
    /// Confirmation that an immutable session artifact was deleted.
    pub fn new(id: String, object: Object, deleted: bool) -> DeletedSessionArtifactResource {
        DeletedSessionArtifactResource {
            id,
            object,
            deleted,
        }
    }
}
/// The object type. Always `agent.session.artifact.deleted`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "agent.session.artifact.deleted")]
    AgentSessionArtifactDeleted,
}

impl Default for Object {
    fn default() -> Object {
        Self::AgentSessionArtifactDeleted
    }
}

impl std::fmt::Display for DeletedSessionArtifactResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
