/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeletedVideoResource : Confirmation payload returned after deleting a video.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct DeletedVideoResource {
    /// The object type that signals the deletion response.
    #[serde(rename = "object")]
    pub object: Object,
    /// Indicates that the video resource was deleted.
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// Identifier of the deleted video.
    #[serde(rename = "id")]
    pub id: String,
}

impl DeletedVideoResource {
    /// Confirmation payload returned after deleting a video.
    pub fn new(object: Object, deleted: bool, id: String) -> DeletedVideoResource {
        DeletedVideoResource {
            object,
            deleted,
            id,
        }
    }
}
/// The object type that signals the deletion response.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "video.deleted")]
    VideoDeleted,
}

impl Default for Object {
    fn default() -> Object {
        Self::VideoDeleted
    }
}

impl std::fmt::Display for DeletedVideoResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
