/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeletedVaultResource : Confirmation that a vault was deleted.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct DeletedVaultResource {
    /// The ID of the deleted vault.
    #[serde(rename = "id")]
    pub id: String,
    /// The object type. Always `vault.deleted`.
    #[serde(rename = "object")]
    pub object: Object,
    /// Whether the resource was deleted. Always `true`.
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl DeletedVaultResource {
    /// Confirmation that a vault was deleted.
    pub fn new(id: String, object: Object, deleted: bool) -> DeletedVaultResource {
        DeletedVaultResource {
            id,
            object,
            deleted,
        }
    }
}
/// The object type. Always `vault.deleted`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "vault.deleted")]
    VaultDeleted,
}

impl Default for Object {
    fn default() -> Object {
        Self::VaultDeleted
    }
}

impl std::fmt::Display for DeletedVaultResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
