/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnvironmentParamNone : Runs the agent without an execution environment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct EnvironmentParamNone {
    /// The type of the object. Always `none`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl EnvironmentParamNone {
    /// Runs the agent without an execution environment.
    pub fn new(r#type: Type) -> EnvironmentParamNone {
        EnvironmentParamNone { r#type }
    }
}
/// The type of the object. Always `none`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "none")]
    None,
}

impl Default for Type {
    fn default() -> Type {
        Self::None
    }
}

impl std::fmt::Display for EnvironmentParamNone {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
