/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorBodyResource : Details about an API error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ErrorBodyResource {
    /// The error type.
    #[serde(rename = "type")]
    pub r#type: String,
    /// A machine-readable error code.
    #[serde(rename = "code")]
    pub code: String,
    /// A human-readable error message.
    #[serde(rename = "message")]
    pub message: String,
    /// The request parameter that caused the error, or null for a request-wide error.
    #[serde(rename = "param", deserialize_with = "Option::deserialize")]
    pub param: Option<String>,
}

impl ErrorBodyResource {
    /// Details about an API error.
    pub fn new(
        r#type: String,
        code: String,
        message: String,
        param: Option<String>,
    ) -> ErrorBodyResource {
        ErrorBodyResource {
            r#type,
            code,
            message,
            param,
        }
    }
}

impl std::fmt::Display for ErrorBodyResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
