/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExternalStorageResponseProvider {
    AwsExternalStorageProviderResponse(Box<models::AwsExternalStorageProviderResponse>),
    AzureExternalStorageProviderResponse(Box<models::AzureExternalStorageProviderResponse>),
    GcpExternalStorageProviderResponse(Box<models::GcpExternalStorageProviderResponse>),
}

impl Default for ExternalStorageResponseProvider {
    fn default() -> Self {
        Self::AwsExternalStorageProviderResponse(Default::default())
    }
}
