/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileAnnotationSource : Attachment source referenced by an annotation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct FileAnnotationSource {
    /// Type discriminator that is always `file`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Filename referenced by the annotation.
    #[serde(rename = "filename")]
    pub filename: String,
}

impl FileAnnotationSource {
    /// Attachment source referenced by an annotation.
    pub fn new(r#type: Type, filename: String) -> FileAnnotationSource {
        FileAnnotationSource {
            r#type,
            filename,
        }
    }
}
/// Type discriminator that is always `file`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}



impl std::fmt::Display for FileAnnotationSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
