/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FineTuneDpoMethod : Configuration for the DPO fine-tuning method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct FineTuneDpoMethod {
    #[serde(rename = "hyperparameters", skip_serializing_if = "Option::is_none")]
    pub hyperparameters: Option<Box<models::FineTuneDpoHyperparameters>>,
}

impl FineTuneDpoMethod {
    /// Configuration for the DPO fine-tuning method.
    pub fn new() -> FineTuneDpoMethod {
        FineTuneDpoMethod {
            hyperparameters: None,
        }
    }
}

