/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FineTuneSupervisedMethod : Configuration for the supervised fine-tuning method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct FineTuneSupervisedMethod {
    #[serde(rename = "hyperparameters", skip_serializing_if = "Option::is_none")]
    pub hyperparameters: Option<Box<models::FineTuneSupervisedHyperparameters>>,
}

impl FineTuneSupervisedMethod {
    /// Configuration for the supervised fine-tuning method.
    pub fn new() -> FineTuneSupervisedMethod {
        FineTuneSupervisedMethod {
            hyperparameters: None,
        }
    }
}



impl std::fmt::Display for FineTuneSupervisedMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
