/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FineTuningJobHyperparametersBatchSize : Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct FineTuningJobHyperparametersBatchSize {}

impl FineTuningJobHyperparametersBatchSize {
    /// Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance.
    pub fn new() -> FineTuningJobHyperparametersBatchSize {
        FineTuningJobHyperparametersBatchSize {}
    }
}
