/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FineTuningJobHyperparameters : The hyperparameters used for the fine-tuning job. This value will only be returned when running `supervised` jobs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct FineTuningJobHyperparameters {
    #[serde(rename = "batch_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<Option<Box<models::Auto>>>,
    #[serde(rename = "learning_rate_multiplier", skip_serializing_if = "Option::is_none")]
    pub learning_rate_multiplier: Option<Box<models::CreateFineTuningJobRequestHyperparametersLearningRateMultiplier>>,
    #[serde(rename = "n_epochs", skip_serializing_if = "Option::is_none")]
    pub n_epochs: Option<Box<models::CreateFineTuningJobRequestHyperparametersNEpochs>>,
}

impl FineTuningJobHyperparameters {
    /// The hyperparameters used for the fine-tuning job. This value will only be returned when running `supervised` jobs.
    pub fn new() -> FineTuningJobHyperparameters {
        FineTuningJobHyperparameters {
            batch_size: None,
            learning_rate_multiplier: None,
            n_epochs: None,
        }
    }
}



impl std::fmt::Display for FineTuningJobHyperparameters {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
