/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionShellToolParam : A tool that allows the model to execute shell commands.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct FunctionShellToolParam {
    /// The type of the shell tool. Always `shell`.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(
        rename = "environment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub environment: Option<Option<Box<models::FunctionShellToolParamEnvironment>>>,
}

impl FunctionShellToolParam {
    /// A tool that allows the model to execute shell commands.
    pub fn new(r#type: Type) -> FunctionShellToolParam {
        FunctionShellToolParam {
            r#type,
            environment: None,
        }
    }
}
/// The type of the shell tool. Always `shell`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "shell")]
    Shell,
}

impl Default for Type {
    fn default() -> Type {
        Self::Shell
    }
}

impl std::fmt::Display for FunctionShellToolParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
