/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupUserAssignment : Confirmation payload returned after adding a user to a group.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct GroupUserAssignment {
    /// Always `group.user`.
    #[serde(rename = "object")]
    pub object: Object,
    /// Identifier of the user that was added.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Identifier of the group the user was added to.
    #[serde(rename = "group_id")]
    pub group_id: String,
}

impl GroupUserAssignment {
    /// Confirmation payload returned after adding a user to a group.
    pub fn new(object: Object, user_id: String, group_id: String) -> GroupUserAssignment {
        GroupUserAssignment {
            object,
            user_id,
            group_id,
        }
    }
}
/// Always `group.user`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "group.user")]
    GroupUser,
}

impl Default for Object {
    fn default() -> Object {
        Self::GroupUser
    }
}

impl std::fmt::Display for GroupUserAssignment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
