/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostedEnvironmentFileParamInline : A file supplied directly as standard-base64 data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct HostedEnvironmentFileParamInline {
    /// The type of the object. Always `inline`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The standard-base64-encoded file contents.
    #[serde(rename = "data")]
    pub data: String,
    /// The absolute destination path inside `/workspace`.
    #[serde(rename = "path")]
    pub path: String,
}

impl HostedEnvironmentFileParamInline {
    /// A file supplied directly as standard-base64 data.
    pub fn new(r#type: Type, data: String, path: String) -> HostedEnvironmentFileParamInline {
        HostedEnvironmentFileParamInline { r#type, data, path }
    }
}
/// The type of the object. Always `inline`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "inline")]
    Inline,
}

impl Default for Type {
    fn default() -> Type {
        Self::Inline
    }
}

impl std::fmt::Display for HostedEnvironmentFileParamInline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
