/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageGenToolInputImageMask : Optional mask for inpainting. Contains `image_url` (string, optional) and `file_id` (string, optional). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ImageGenToolInputImageMask {
    /// Base64-encoded mask image. 
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// File ID for the mask image. 
    #[serde(rename = "file_id", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
}

impl ImageGenToolInputImageMask {
    /// Optional mask for inpainting. Contains `image_url` (string, optional) and `file_id` (string, optional). 
    pub fn new() -> ImageGenToolInputImageMask {
        ImageGenToolInputImageMask {
            image_url: None,
            file_id: None,
        }
    }
}



impl std::fmt::Display for ImageGenToolInputImageMask {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
