/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageGenUsage : For `gpt-image-1` only, the token usage information for the image generation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ImageGenUsage {
    /// The number of tokens (images and text) in the input prompt.
    #[serde(rename = "input_tokens")]
    pub input_tokens: i32,
    /// The total number of tokens (images and text) used for the image generation.
    #[serde(rename = "total_tokens")]
    pub total_tokens: i32,
    /// The number of output tokens generated by the model.
    #[serde(rename = "output_tokens")]
    pub output_tokens: i32,
    #[serde(rename = "input_tokens_details")]
    pub input_tokens_details: Box<models::ImageGenInputUsageDetails>,
}

impl ImageGenUsage {
    /// For `gpt-image-1` only, the token usage information for the image generation.
    pub fn new(
        input_tokens: i32,
        total_tokens: i32,
        output_tokens: i32,
        input_tokens_details: models::ImageGenInputUsageDetails,
    ) -> ImageGenUsage {
        ImageGenUsage {
            input_tokens,
            total_tokens,
            output_tokens,
            input_tokens_details: Box::new(input_tokens_details),
        }
    }
}
