/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiveTransportDtmfSend : A SIP DTMF keypress successfully sent by the hosted tool. Delivered only to sideband observers; this is not a client command.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LiveTransportDtmfSend {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "event")]
    pub event: String,
}

impl LiveTransportDtmfSend {
    /// A SIP DTMF keypress successfully sent by the hosted tool. Delivered only to sideband observers; this is not a client command.
    pub fn new(r#type: Type, event_id: String, event: String) -> LiveTransportDtmfSend {
        LiveTransportDtmfSend {
            r#type,
            event_id,
            event,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "transport.dtmf.send")]
    TransportDtmfSend,
}

impl Default for Type {
    fn default() -> Type {
        Self::TransportDtmfSend
    }
}

impl std::fmt::Display for LiveTransportDtmfSend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
