/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiveAudioFormat : Audio encoding and sample rate for audio sent and received over a Live WebSocket connection. WebRTC and SIP negotiate their media format separately.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LiveAudioFormat {
    LiveSessionAudioFormatPcmParam(Box<models::LiveSessionAudioFormatPcmParam>),
    LiveSessionAudioFormatPcmuParam(Box<models::LiveSessionAudioFormatPcmuParam>),
    LiveSessionAudioFormatPcmaParam(Box<models::LiveSessionAudioFormatPcmaParam>),
}

impl Default for LiveAudioFormat {
    fn default() -> Self {
        Self::LiveSessionAudioFormatPcmParam(Default::default())
    }
}
