/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LiveResponsesDelegationSettingsInputParamToolsInner {
    LiveFunctionToolInputParam(Box<models::LiveFunctionToolInputParam>),
    LiveWebSearchToolInputParam(Box<models::LiveWebSearchToolInputParam>),
    LiveFileSearchToolInputParam(Box<models::LiveFileSearchToolInputParam>),
    LiveCodeInterpreterToolInputParam(Box<models::LiveCodeInterpreterToolInputParam>),
    LiveHostedShellToolInputParam(Box<models::LiveHostedShellToolInputParam>),
    LiveImageGenerationToolInputParam(Box<models::LiveImageGenerationToolInputParam>),
    LiveMcpToolInputParam(Box<models::LiveMcpToolInputParam>),
    LiveCustomToolInputParam(Box<models::LiveCustomToolInputParam>),
    LiveNamespaceToolInputParam(Box<models::LiveNamespaceToolInputParam>),
    LiveToolSearchToolInputParam(Box<models::LiveToolSearchToolInputParam>),
    LiveProgrammaticToolInputParam(Box<models::LiveProgrammaticToolInputParam>),
    LiveComputerToolInputParam(Box<models::LiveComputerToolInputParam>),
    LiveApplyPatchToolInputParam(Box<models::LiveApplyPatchToolInputParam>),
}

impl Default for LiveResponsesDelegationSettingsInputParamToolsInner {
    fn default() -> Self {
        Self::LiveFunctionToolInputParam(Default::default())
    }
}
