/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiveInputAudioMuteParam : Mute audio input to the Live model without closing the session. The server acknowledges with `session.input_audio.muted`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LiveInputAudioMuteParam {
    /// Optional client identifier for correlating this command with a server event's client_event_id or error.client_event_id.
    #[serde(
        rename = "event_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub event_id: Option<Option<String>>,
    /// The Live client event type. Always `session.input_audio.mute`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl LiveInputAudioMuteParam {
    /// Mute audio input to the Live model without closing the session. The server acknowledges with `session.input_audio.muted`.
    pub fn new(r#type: Type) -> LiveInputAudioMuteParam {
        LiveInputAudioMuteParam {
            event_id: None,
            r#type,
        }
    }
}
/// The Live client event type. Always `session.input_audio.mute`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.input_audio.mute")]
    SessionInputAudioMute,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionInputAudioMute
    }
}

impl std::fmt::Display for LiveInputAudioMuteParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
