/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiveAllowedServerEventParam : A Live server event selector for the WebRTC frontend data channel.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LiveAllowedServerEventParam {
    /// The outer Live server event type. Use 'response.event' for Responses events.
    #[serde(rename = "type")]
    pub r#type: String,
    /// The nested Responses event type. Required when type is 'response.event'; forbidden for other event types.
    #[serde(rename = "response_event", skip_serializing_if = "Option::is_none")]
    pub response_event: Option<String>,
}

impl LiveAllowedServerEventParam {
    /// A Live server event selector for the WebRTC frontend data channel.
    pub fn new(r#type: String) -> LiveAllowedServerEventParam {
        LiveAllowedServerEventParam {
            r#type,
            response_event: None,
        }
    }
}

impl std::fmt::Display for LiveAllowedServerEventParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
