/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LiveThinkingAppendParam : Provide silent reasoning or progress context to the Live model, optionally for an existing client delegation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LiveThinkingAppendParam {
    /// Optional client identifier for correlating this command with a server event's client_event_id or error.client_event_id.
    #[serde(
        rename = "event_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub event_id: Option<Option<String>>,
    /// The Live client event type. Always `session.thinking.append`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Required, nullable. Set null for general session context, or use the ID from session.delegation.created for an existing client delegation. Non-null IDs are not accepted with Responses delegation.
    #[serde(rename = "delegation_id", deserialize_with = "Option::deserialize")]
    pub delegation_id: Option<String>,
    /// Silent reasoning or progress context, limited to 500 tokens. It does not directly request speech, but can influence later speech and is not a secrecy boundary.
    #[serde(rename = "content")]
    pub content: String,
}

impl LiveThinkingAppendParam {
    /// Provide silent reasoning or progress context to the Live model, optionally for an existing client delegation.
    pub fn new(
        r#type: Type,
        delegation_id: Option<String>,
        content: String,
    ) -> LiveThinkingAppendParam {
        LiveThinkingAppendParam {
            event_id: None,
            r#type,
            delegation_id,
            content,
        }
    }
}
/// The Live client event type. Always `session.thinking.append`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.thinking.append")]
    SessionThinkingAppend,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionThinkingAppend
    }
}

impl std::fmt::Display for LiveThinkingAppendParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
