/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LiveReasoningSummary {
    #[serde(rename = "concise")]
    Concise,
    #[serde(rename = "detailed")]
    Detailed,
    #[serde(rename = "auto")]
    Auto,
}

impl std::fmt::Display for LiveReasoningSummary {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Concise => write!(f, "concise"),
            Self::Detailed => write!(f, "detailed"),
            Self::Auto => write!(f, "auto"),
        }
    }
}

impl Default for LiveReasoningSummary {
    fn default() -> LiveReasoningSummary {
        Self::Concise
    }
}
