/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct LiveSpecificWebSearchPreviewParam {
    /// The tool to call. Always `web_search_preview`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl LiveSpecificWebSearchPreviewParam {
    pub fn new(r#type: Type) -> LiveSpecificWebSearchPreviewParam {
        LiveSpecificWebSearchPreviewParam { r#type }
    }
}
/// The tool to call. Always `web_search_preview`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "web_search_preview")]
    WebSearchPreview,
}

impl Default for Type {
    fn default() -> Type {
        Self::WebSearchPreview
    }
}

impl std::fmt::Display for LiveSpecificWebSearchPreviewParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
