/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// McpTransportResource : The transport used to connect to an MCP server.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum McpTransportResource {
    Http(Box<models::McpTransportResourceHttp>),
    Stdio(Box<models::McpTransportResourceStdio>),
}

impl Default for McpTransportResource {
    fn default() -> Self {
        Self::Http(Default::default())
    }
}
