/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// McpOauthTokenEndpointAuthResourceClientSecretPost : Sends the client ID and secret in the token request body.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct McpOauthTokenEndpointAuthResourceClientSecretPost {
    /// The type of the object. Always `client_secret_post`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl McpOauthTokenEndpointAuthResourceClientSecretPost {
    /// Sends the client ID and secret in the token request body.
    pub fn new(r#type: Type) -> McpOauthTokenEndpointAuthResourceClientSecretPost {
        McpOauthTokenEndpointAuthResourceClientSecretPost { r#type }
    }
}
/// The type of the object. Always `client_secret_post`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "client_secret_post")]
    ClientSecretPost,
}

impl Default for Type {
    fn default() -> Type {
        Self::ClientSecretPost
    }
}

impl std::fmt::Display for McpOauthTokenEndpointAuthResourceClientSecretPost {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
