/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageStreamEvent {
    Object012(serde_json::Value),
    Object1(Box<models::Object1>),
    Object2(Box<models::Object2>),
    Object3(Box<models::Object3>),
    Object4(Box<models::Object4>),
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "thread.message.incomplete")]
    ThreadMessageIncomplete,
}

impl Default for Event {
    fn default() -> Event {
        Self::ThreadMessageIncomplete
    }
}
