/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct MessageDeltaContentImageUrlObjectImageUrl {
    /// The URL of the image, must be a supported image types: jpeg, jpg, png, gif, webp.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Specifies the detail level of the image. `low` uses fewer tokens, you can opt in to high resolution using `high`.
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<Detail>,
}

impl MessageDeltaContentImageUrlObjectImageUrl {
    pub fn new() -> MessageDeltaContentImageUrlObjectImageUrl {
        MessageDeltaContentImageUrlObjectImageUrl {
            url: None,
            detail: None,
        }
    }
}
/// Specifies the detail level of the image. `low` uses fewer tokens, you can opt in to high resolution using `high`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Detail {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "high")]
    High,
}

impl Default for Detail {
    fn default() -> Detail {
        Self::Auto
    }
}



impl std::fmt::Display for MessageDeltaContentImageUrlObjectImageUrl {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
