/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessageItemResource : A user or assistant message recorded in a session.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct MessageItemResource {
    /// The item type. Always `message`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of this item, or null for legacy user messages whose ID was not recorded.
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    /// The ID of the turn that contains this item.
    #[serde(rename = "turn_id")]
    pub turn_id: String,
    #[serde(rename = "role")]
    pub role: models::SessionMessageRoleResource,
    /// The content of the message. User messages contain input text or images; assistant messages contain output text.
    #[serde(rename = "content")]
    pub content: Vec<models::MessageContentResource>,
    #[serde(rename = "status")]
    pub status: models::OutputItemStatusResource,
    #[serde(rename = "phase", deserialize_with = "Option::deserialize")]
    pub phase: Option<models::MessagePhaseResource>,
}

impl MessageItemResource {
    /// A user or assistant message recorded in a session.
    pub fn new(
        r#type: Type,
        id: Option<String>,
        turn_id: String,
        role: models::SessionMessageRoleResource,
        content: Vec<models::MessageContentResource>,
        status: models::OutputItemStatusResource,
        phase: Option<models::MessagePhaseResource>,
    ) -> MessageItemResource {
        MessageItemResource {
            r#type,
            id,
            turn_id,
            role,
            content,
            status,
            phase,
        }
    }
}
/// The item type. Always `message`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "message")]
    Message,
}

impl Default for Type {
    fn default() -> Type {
        Self::Message
    }
}

impl std::fmt::Display for MessageItemResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
