/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct MisalignmentErrorDetailsResource {
    #[serde(rename = "error_type", skip_serializing_if = "Option::is_none")]
    pub error_type: Option<Box<models::MisalignmentErrorType>>,
    /// The public explanation for this block.
    #[serde(
        rename = "detailed_explanation",
        skip_serializing_if = "Option::is_none"
    )]
    pub detailed_explanation: Option<String>,
    #[serde(rename = "steer", skip_serializing_if = "Option::is_none")]
    pub steer: Option<Box<models::MisalignmentSteer>>,
}

impl MisalignmentErrorDetailsResource {
    pub fn new() -> MisalignmentErrorDetailsResource {
        MisalignmentErrorDetailsResource {
            error_type: None,
            detailed_explanation: None,
            steer: None,
        }
    }
}

impl std::fmt::Display for MisalignmentErrorDetailsResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
