/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModerationOutput : Moderation for the response output.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModerationOutput {
    ModerationResultBody(Box<models::ModerationResultBody>),
    ModerationErrorBody(Box<models::ModerationErrorBody>),
}

impl Default for ModerationOutput {
    fn default() -> Self {
        Self::ModerationResultBody(Default::default())
    }
}
