/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultiAgentConfigCurrentParam : Explicit configuration for creating and coordinating subagents.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct MultiAgentConfigCurrentParam {
    /// Whether subagent tools are enabled.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Maximum number of subagents that may run concurrently. Defaults to 6.
    #[serde(
        rename = "max_concurrent_subagents",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_concurrent_subagents: Option<i64>,
}

impl MultiAgentConfigCurrentParam {
    /// Explicit configuration for creating and coordinating subagents.
    pub fn new(enabled: bool) -> MultiAgentConfigCurrentParam {
        MultiAgentConfigCurrentParam {
            enabled,
            max_concurrent_subagents: None,
        }
    }
}

impl std::fmt::Display for MultiAgentConfigCurrentParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
