/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NamespaceToolParam : Groups function/custom tools under a shared namespace.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct NamespaceToolParam {
    /// The type of the tool. Always `namespace`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The namespace name used in tool calls (for example, `crm`).
    #[serde(rename = "name")]
    pub name: String,
    /// A description of the namespace shown to the model.
    #[serde(rename = "description")]
    pub description: String,
    /// The function/custom tools available inside this namespace.
    #[serde(rename = "tools")]
    pub tools: Vec<models::NamespaceToolParamToolsInner>,
}

impl NamespaceToolParam {
    /// Groups function/custom tools under a shared namespace.
    pub fn new(
        r#type: Type,
        name: String,
        description: String,
        tools: Vec<models::NamespaceToolParamToolsInner>,
    ) -> NamespaceToolParam {
        NamespaceToolParam {
            r#type,
            name,
            description,
            tools,
        }
    }
}
/// The type of the tool. Always `namespace`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "namespace")]
    Namespace,
}

impl Default for Type {
    fn default() -> Type {
        Self::Namespace
    }
}

impl std::fmt::Display for NamespaceToolParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
