/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NetworkPolicyParam : Network access for an OpenAI-hosted environment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct NetworkPolicyParam {
    #[serde(rename = "access")]
    pub access: models::NetworkAccessParam,
    /// Domains the environment may access when network access is restricted.
    #[serde(
        rename = "allowed_domains",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_domains: Option<Option<Vec<String>>>,
    /// Domains blocked for both executor and browser when access is restricted. A nonempty list requires `access: restricted` and cannot be combined with nonempty `allowed_domains`. Wildcard domains are not supported.
    #[serde(
        rename = "blocked_domains",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blocked_domains: Option<Option<Vec<String>>>,
}

impl NetworkPolicyParam {
    /// Network access for an OpenAI-hosted environment.
    pub fn new(access: models::NetworkAccessParam) -> NetworkPolicyParam {
        NetworkPolicyParam {
            access,
            allowed_domains: None,
            blocked_domains: None,
        }
    }
}

impl std::fmt::Display for NetworkPolicyParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
