/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NetworkAccessResource : The network access mode for an OpenAI-hosted environment.
/// The network access mode for an OpenAI-hosted environment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NetworkAccessResource {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "restricted")]
    Restricted,
}

impl std::fmt::Display for NetworkAccessResource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enabled => write!(f, "enabled"),
            Self::Disabled => write!(f, "disabled"),
            Self::Restricted => write!(f, "restricted"),
        }
    }
}

impl Default for NetworkAccessResource {
    fn default() -> NetworkAccessResource {
        Self::Enabled
    }
}
