/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Object08 : For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Object08 {
    /// A machine-readable error code.
    #[serde(rename = "code")]
    pub code: String,
    /// A human-readable error message.
    #[serde(rename = "message")]
    pub message: String,
    /// The parameter that was invalid, usually `training_file` or `validation_file`. This field will be null if the failure was not parameter-specific.
    #[serde(rename = "param", deserialize_with = "Option::deserialize")]
    pub param: Option<String>,
}

impl Object08 {
    /// For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.
    pub fn new(code: String, message: String, param: Option<String>) -> Object08 {
        Object08 {
            code,
            message,
            param,
        }
    }
}

impl std::fmt::Display for Object08 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
