/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Object05 : Log probability information for the choice.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Object05 {
    /// A list of message content tokens with log probability information.
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<Vec<models::ChatCompletionTokenLogprob>>,
    /// A list of message refusal tokens with log probability information.
    #[serde(rename = "refusal", deserialize_with = "Option::deserialize")]
    pub refusal: Option<Vec<models::ChatCompletionTokenLogprob>>,
}

impl Object05 {
    /// Log probability information for the choice.
    pub fn new(
        content: Option<Vec<models::ChatCompletionTokenLogprob>>,
        refusal: Option<Vec<models::ChatCompletionTokenLogprob>>,
    ) -> Object05 {
        Object05 { content, refusal }
    }
}

impl std::fmt::Display for Object05 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
