/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Object1 : The SIP transport. Trunk credentials and SDP are not returned.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Object1 {
    /// The transport used for the Live session. Always `sip`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Object1 {
    /// The SIP transport. Trunk credentials and SDP are not returned.
    pub fn new(r#type: Type) -> Object1 {
        Object1 { r#type }
    }
}
/// The transport used for the Live session. Always `sip`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "sip")]
    Sip,
}

impl Default for Type {
    fn default() -> Type {
        Self::Sip
    }
}

impl std::fmt::Display for Object1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
