/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Object8 : Occurs when a [run](/docs/api-reference/runs/object) is cancelled.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct Object8 {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "data")]
    pub data: Box<models::RunObject>,
}

impl Object8 {
    /// Occurs when a [run](/docs/api-reference/runs/object) is cancelled.
    pub fn new(event: Event, data: models::RunObject) -> Object8 {
        Object8 {
            event,
            data: Box::new(data),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "thread.run.cancelled")]
    ThreadRunCancelled,
}

impl Default for Event {
    fn default() -> Event {
        Self::ThreadRunCancelled
    }
}

impl std::fmt::Display for Object8 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
