/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct OrganizationProjectCertificateDeactivationResponse {
    /// The project certificate deactivation result type.
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "data")]
    pub data: Vec<models::OrganizationProjectCertificate>,
}

impl OrganizationProjectCertificateDeactivationResponse {
    pub fn new(
        object: Object,
        data: Vec<models::OrganizationProjectCertificate>,
    ) -> OrganizationProjectCertificateDeactivationResponse {
        OrganizationProjectCertificateDeactivationResponse { object, data }
    }
}
/// The project certificate deactivation result type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "organization.project.certificate.deactivation")]
    OrganizationProjectCertificateDeactivation,
}

impl Default for Object {
    fn default() -> Object {
        Self::OrganizationProjectCertificateDeactivation
    }
}

impl std::fmt::Display for OrganizationProjectCertificateDeactivationResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
