/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct OutputTokensDetailsResource {
    #[serde(rename = "reasoning_tokens")]
    pub reasoning_tokens: i64,
}

impl OutputTokensDetailsResource {
    pub fn new(reasoning_tokens: i64) -> OutputTokensDetailsResource {
        OutputTokensDetailsResource { reasoning_tokens }
    }
}

impl std::fmt::Display for OutputTokensDetailsResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
