/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PersistedMcpTransportResourceStdio : Starts an MCP server as a local process.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PersistedMcpTransportResourceStdio {
    /// The type of the object. Always `stdio`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The command used to start the MCP server.
    #[serde(rename = "command")]
    pub command: String,
    /// Arguments passed to the MCP server command.
    #[serde(rename = "args")]
    pub args: Vec<String>,
    /// The working directory used to start the MCP server.
    #[serde(rename = "cwd")]
    pub cwd: String,
    /// Environment variable names inherited from the execution environment.
    #[serde(rename = "env_vars")]
    pub env_vars: Vec<String>,
}

impl PersistedMcpTransportResourceStdio {
    /// Starts an MCP server as a local process.
    pub fn new(
        r#type: Type,
        command: String,
        args: Vec<String>,
        cwd: String,
        env_vars: Vec<String>,
    ) -> PersistedMcpTransportResourceStdio {
        PersistedMcpTransportResourceStdio {
            r#type,
            command,
            args,
            cwd,
            env_vars,
        }
    }
}
/// The type of the object. Always `stdio`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "stdio")]
    Stdio,
}

impl Default for Type {
    fn default() -> Type {
        Self::Stdio
    }
}

impl std::fmt::Display for PersistedMcpTransportResourceStdio {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
