/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PersistedAgentToolResourceWebSearch : Web search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PersistedAgentToolResourceWebSearch {
    /// The type of the object. Always `web_search`.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "mode")]
    pub mode: models::WebSearchModeResource,
    #[serde(rename = "context_size")]
    pub context_size: models::WebSearchContextSizeResource,
    /// Allowed search domains, or `null` when the search is unrestricted.
    #[serde(rename = "allowed_domains", deserialize_with = "Option::deserialize")]
    pub allowed_domains: Option<Vec<String>>,
    #[serde(rename = "location", deserialize_with = "Option::deserialize")]
    pub location: Option<models::WebSearchLocationResource>,
}

impl PersistedAgentToolResourceWebSearch {
    /// Web search.
    pub fn new(
        r#type: Type,
        mode: models::WebSearchModeResource,
        context_size: models::WebSearchContextSizeResource,
        allowed_domains: Option<Vec<String>>,
        location: Option<models::WebSearchLocationResource>,
    ) -> PersistedAgentToolResourceWebSearch {
        PersistedAgentToolResourceWebSearch {
            r#type,
            mode,
            context_size,
            allowed_domains,
            location,
        }
    }
}
/// The type of the object. Always `web_search`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "web_search")]
    WebSearch,
}

impl Default for Type {
    fn default() -> Type {
        Self::WebSearch
    }
}

impl std::fmt::Display for PersistedAgentToolResourceWebSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
