/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectApiKeyOwnerServiceAccount : The service account that owns a project API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ProjectApiKeyOwnerServiceAccount {
    /// The identifier, which can be referenced in API endpoints
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the service account.
    #[serde(rename = "name")]
    pub name: String,
    /// The Unix timestamp (in seconds) of when the service account was created.
    #[serde(rename = "created_at")]
    pub created_at: i32,
    /// The service account's project role.
    #[serde(rename = "role")]
    pub role: String,
}

impl ProjectApiKeyOwnerServiceAccount {
    /// The service account that owns a project API key.
    pub fn new(
        id: String,
        name: String,
        created_at: i32,
        role: String,
    ) -> ProjectApiKeyOwnerServiceAccount {
        ProjectApiKeyOwnerServiceAccount {
            id,
            name,
            created_at,
            role,
        }
    }
}

impl std::fmt::Display for ProjectApiKeyOwnerServiceAccount {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
