/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ProjectModelPermissionsUpdateRequest {
    /// The model permissions mode to apply.
    #[serde(rename = "mode")]
    pub mode: Mode,
    /// The model IDs included in this permissions policy.
    #[serde(rename = "model_ids")]
    pub model_ids: Vec<String>,
}

impl ProjectModelPermissionsUpdateRequest {
    pub fn new(mode: Mode, model_ids: Vec<String>) -> ProjectModelPermissionsUpdateRequest {
        ProjectModelPermissionsUpdateRequest { mode, model_ids }
    }
}
/// The model permissions mode to apply.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "allow_list")]
    AllowList,
    #[serde(rename = "deny_list")]
    DenyList,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::AllowList
    }
}

impl std::fmt::Display for ProjectModelPermissionsUpdateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
