/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ProjectServiceAccountCreateResponse {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Service accounts created with default project membership have role `member`. Accounts created with `create_service_account_only` have role `none`.
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "api_key", deserialize_with = "Option::deserialize")]
    pub api_key: Option<Box<models::ProjectServiceAccountApiKey>>,
}

impl ProjectServiceAccountCreateResponse {
    pub fn new(
        object: Object,
        id: String,
        name: String,
        role: Role,
        created_at: i32,
        api_key: Option<models::ProjectServiceAccountApiKey>,
    ) -> ProjectServiceAccountCreateResponse {
        ProjectServiceAccountCreateResponse {
            object,
            id,
            name,
            role,
            created_at,
            api_key: api_key.map(Box::new),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "organization.project.service_account")]
    OrganizationProjectServiceAccount,
}

impl Default for Object {
    fn default() -> Object {
        Self::OrganizationProjectServiceAccount
    }
}
/// Service accounts created with default project membership have role `member`. Accounts created with `create_service_account_only` have role `none`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "none")]
    None,
}

impl Default for Role {
    fn default() -> Role {
        Self::Member
    }
}

impl std::fmt::Display for ProjectServiceAccountCreateResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
