/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PublicRotateSecretBody {
    /// Whether to keep the previous signing secret valid for 24 hours after rotation. Defaults to false, which invalidates the previous secret immediately.
    #[serde(
        rename = "keep_old_secret_active_for_24_hours",
        skip_serializing_if = "Option::is_none"
    )]
    pub keep_old_secret_active_for_24_hours: Option<bool>,
}

impl PublicRotateSecretBody {
    pub fn new() -> PublicRotateSecretBody {
        PublicRotateSecretBody {
            keep_old_secret_active_for_24_hours: None,
        }
    }
}

impl std::fmt::Display for PublicRotateSecretBody {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
