/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PublicDecisionsUsageResponseResource {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "next_page", deserialize_with = "Option::deserialize")]
    pub next_page: Option<String>,
    #[serde(rename = "data")]
    pub data: Vec<models::DecisionsUsageBucket>,
}

impl PublicDecisionsUsageResponseResource {
    pub fn new(
        object: Object,
        has_more: bool,
        next_page: Option<String>,
        data: Vec<models::DecisionsUsageBucket>,
    ) -> PublicDecisionsUsageResponseResource {
        PublicDecisionsUsageResponseResource {
            object,
            has_more,
            next_page,
            data,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "page")]
    Page,
}

impl Default for Object {
    fn default() -> Object {
        Self::Page
    }
}

impl std::fmt::Display for PublicDecisionsUsageResponseResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
