/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RealtimeTranscriptionSessionCreateResponseGaAudioInput {
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Box<models::RealtimeAudioFormats>>,
    #[serde(rename = "transcription", skip_serializing_if = "Option::is_none")]
    pub transcription: Option<Box<models::AudioTranscription>>,
    #[serde(rename = "noise_reduction", skip_serializing_if = "Option::is_none")]
    pub noise_reduction: Option<Box<models::RealtimeSessionCreateResponseAudioInputNoiseReduction>>,
    #[serde(rename = "turn_detection", skip_serializing_if = "Option::is_none")]
    pub turn_detection: Option<Box<models::RealtimeSessionCreateRequestTurnDetection>>,
}

impl RealtimeTranscriptionSessionCreateResponseGaAudioInput {
    pub fn new() -> RealtimeTranscriptionSessionCreateResponseGaAudioInput {
        RealtimeTranscriptionSessionCreateResponseGaAudioInput {
            format: None,
            transcription: None,
            noise_reduction: None,
            turn_detection: None,
        }
    }
}

impl std::fmt::Display for RealtimeTranscriptionSessionCreateResponseGaAudioInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
