/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeTranslationSession : A Realtime translation session. Translation sessions continuously translate input audio into the configured output language.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RealtimeTranslationSession {
    /// Unique identifier for the session that looks like `sess_1234567890abcdef`.
    #[serde(rename = "id")]
    pub id: String,
    /// The session type. Always `translation` for Realtime translation sessions.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Expiration timestamp for the session, in seconds since epoch.
    #[serde(rename = "expires_at")]
    pub expires_at: i32,
    /// The Realtime translation model used for this session. This field is set at session creation and cannot be changed with `session.update`.
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "audio")]
    pub audio: Box<models::RealtimeTranslationSessionAudio>,
}

impl RealtimeTranslationSession {
    /// A Realtime translation session. Translation sessions continuously translate input audio into the configured output language.
    pub fn new(
        id: String,
        r#type: Type,
        expires_at: i32,
        model: String,
        audio: models::RealtimeTranslationSessionAudio,
    ) -> RealtimeTranslationSession {
        RealtimeTranslationSession {
            id,
            r#type,
            expires_at,
            model,
            audio: Box::new(audio),
        }
    }
}
/// The session type. Always `translation` for Realtime translation sessions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "translation")]
    Translation,
}

impl Default for Type {
    fn default() -> Type {
        Self::Translation
    }
}

impl std::fmt::Display for RealtimeTranslationSession {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
