/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeBetaServerEventInputAudioBufferCleared : Returned when the input audio buffer is cleared by the client with a  `input_audio_buffer.clear` event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RealtimeBetaServerEventInputAudioBufferCleared {
    /// The unique ID of the server event.
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,
}

impl RealtimeBetaServerEventInputAudioBufferCleared {
    /// Returned when the input audio buffer is cleared by the client with a  `input_audio_buffer.clear` event.
    pub fn new(
        event_id: String,
        r#type: Option<serde_json::Value>,
    ) -> RealtimeBetaServerEventInputAudioBufferCleared {
        RealtimeBetaServerEventInputAudioBufferCleared { event_id, r#type }
    }
}
