/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeTranslationServerEventSessionClosed : Returned when a realtime translation session is closed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RealtimeTranslationServerEventSessionClosed {
    /// The unique ID of the server event.
    #[serde(rename = "event_id")]
    pub event_id: String,
    /// The event type, must be `session.closed`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RealtimeTranslationServerEventSessionClosed {
    /// Returned when a realtime translation session is closed.
    pub fn new(event_id: String, r#type: Type) -> RealtimeTranslationServerEventSessionClosed {
        RealtimeTranslationServerEventSessionClosed { event_id, r#type }
    }
}
/// The event type, must be `session.closed`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.closed")]
    SessionClosed,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionClosed
    }
}

impl std::fmt::Display for RealtimeTranslationServerEventSessionClosed {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
