/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeServerEventResponseMcpCallCompleted : Returned when an MCP tool call has completed successfully.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RealtimeServerEventResponseMcpCallCompleted {
    /// The unique ID of the server event.
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,
    /// The index of the output item in the response.
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The ID of the MCP tool call item.
    #[serde(rename = "item_id")]
    pub item_id: String,
}

impl RealtimeServerEventResponseMcpCallCompleted {
    /// Returned when an MCP tool call has completed successfully.
    pub fn new(event_id: String, r#type: Option<serde_json::Value>, output_index: i32, item_id: String) -> RealtimeServerEventResponseMcpCallCompleted {
        RealtimeServerEventResponseMcpCallCompleted {
            event_id,
            r#type,
            output_index,
            item_id,
        }
    }
}



impl std::fmt::Display for RealtimeServerEventResponseMcpCallCompleted {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
