/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RealtimeConversationItemMessageSystemContentInner {
    /// The content type. Always `input_text` for system messages.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// The text content.
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

impl RealtimeConversationItemMessageSystemContentInner {
    pub fn new() -> RealtimeConversationItemMessageSystemContentInner {
        RealtimeConversationItemMessageSystemContentInner {
            r#type: None,
            text: None,
        }
    }
}
/// The content type. Always `input_text` for system messages.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "input_text")]
    InputText,
}

impl Default for Type {
    fn default() -> Type {
        Self::InputText
    }
}

impl std::fmt::Display for RealtimeConversationItemMessageSystemContentInner {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
