/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReasoningItemResource : A reasoning item produced by the agent.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ReasoningItemResource {
    /// The item type. Always `reasoning`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the reasoning item.
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the turn that contains this item.
    #[serde(rename = "turn_id")]
    pub turn_id: String,
    /// The reasoning summaries produced by the agent.
    #[serde(rename = "summary")]
    pub summary: Vec<models::SummaryTextResource>,
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<models::OutputItemStatusResource>,
}

impl ReasoningItemResource {
    /// A reasoning item produced by the agent.
    pub fn new(
        r#type: Type,
        id: String,
        turn_id: String,
        summary: Vec<models::SummaryTextResource>,
        status: Option<models::OutputItemStatusResource>,
    ) -> ReasoningItemResource {
        ReasoningItemResource {
            r#type,
            id,
            turn_id,
            summary,
            status,
        }
    }
}
/// The item type. Always `reasoning`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "reasoning")]
    Reasoning,
}

impl Default for Type {
    fn default() -> Type {
        Self::Reasoning
    }
}

impl std::fmt::Display for ReasoningItemResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
