/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResponseReasoningTextDoneEvent : Emitted when a reasoning text is completed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ResponseReasoningTextDoneEvent {
    /// The type of the event. Always `response.reasoning_text.done`. 
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the item this reasoning text is associated with. 
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The index of the output item this reasoning text is associated with. 
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The index of the reasoning content part. 
    #[serde(rename = "content_index")]
    pub content_index: i32,
    /// The full text of the completed reasoning content. 
    #[serde(rename = "text")]
    pub text: String,
    /// The sequence number of this event. 
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
}

impl ResponseReasoningTextDoneEvent {
    /// Emitted when a reasoning text is completed.
    pub fn new(r#type: Type, item_id: String, output_index: i32, content_index: i32, text: String, sequence_number: i32) -> ResponseReasoningTextDoneEvent {
        ResponseReasoningTextDoneEvent {
            r#type,
            item_id,
            output_index,
            content_index,
            text,
            sequence_number,
        }
    }
}
/// The type of the event. Always `response.reasoning_text.done`. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.reasoning_text.done")]
    ResponseReasoningTextDone,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseReasoningTextDone
    }
}



impl std::fmt::Display for ResponseReasoningTextDoneEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
