/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResponseReasoningSummaryPartDoneEvent : Emitted when a reasoning summary part is completed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ResponseReasoningSummaryPartDoneEvent {
    /// The type of the event. Always `response.reasoning_summary_part.done`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the item this summary part is associated with.
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The index of the output item this summary part is associated with.
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The index of the summary part within the reasoning summary.
    #[serde(rename = "summary_index")]
    pub summary_index: i32,
    /// The sequence number of this event.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
    #[serde(rename = "part")]
    pub part: Box<models::ResponseReasoningSummaryPartDoneEventPart>,
}

impl ResponseReasoningSummaryPartDoneEvent {
    /// Emitted when a reasoning summary part is completed.
    pub fn new(
        r#type: Type,
        item_id: String,
        output_index: i32,
        summary_index: i32,
        sequence_number: i32,
        part: models::ResponseReasoningSummaryPartDoneEventPart,
    ) -> ResponseReasoningSummaryPartDoneEvent {
        ResponseReasoningSummaryPartDoneEvent {
            r#type,
            item_id,
            output_index,
            summary_index,
            sequence_number,
            part: Box::new(part),
        }
    }
}
/// The type of the event. Always `response.reasoning_summary_part.done`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.reasoning_summary_part.done")]
    ResponseReasoningSummaryPartDone,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseReasoningSummaryPartDone
    }
}

impl std::fmt::Display for ResponseReasoningSummaryPartDoneEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
