/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResponseFileSearchCallInProgressEvent : Emitted when a file search call is initiated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ResponseFileSearchCallInProgressEvent {
    /// The type of the event. Always `response.file_search_call.in_progress`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The index of the output item that the file search call is initiated.
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The ID of the output item that the file search call is initiated.
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The sequence number of this event.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
}

impl ResponseFileSearchCallInProgressEvent {
    /// Emitted when a file search call is initiated.
    pub fn new(
        r#type: Type,
        output_index: i32,
        item_id: String,
        sequence_number: i32,
    ) -> ResponseFileSearchCallInProgressEvent {
        ResponseFileSearchCallInProgressEvent {
            r#type,
            output_index,
            item_id,
            sequence_number,
        }
    }
}
/// The type of the event. Always `response.file_search_call.in_progress`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.file_search_call.in_progress")]
    ResponseFileSearchCallInProgress,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseFileSearchCallInProgress
    }
}

impl std::fmt::Display for ResponseFileSearchCallInProgressEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
