/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResponseMcpCallCompletedEvent : Emitted when an MCP  tool call has completed successfully. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ResponseMcpCallCompletedEvent {
    /// The type of the event. Always 'response.mcp_call.completed'.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the MCP tool call item that completed.
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The index of the output item that completed.
    #[serde(rename = "output_index")]
    pub output_index: i32,
    /// The sequence number of this event.
    #[serde(rename = "sequence_number")]
    pub sequence_number: i32,
}

impl ResponseMcpCallCompletedEvent {
    /// Emitted when an MCP  tool call has completed successfully. 
    pub fn new(r#type: Type, item_id: String, output_index: i32, sequence_number: i32) -> ResponseMcpCallCompletedEvent {
        ResponseMcpCallCompletedEvent {
            r#type,
            item_id,
            output_index,
            sequence_number,
        }
    }
}
/// The type of the event. Always 'response.mcp_call.completed'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "response.mcp_call.completed")]
    ResponseMcpCallCompleted,
}

impl Default for Type {
    fn default() -> Type {
        Self::ResponseMcpCallCompleted
    }
}



impl std::fmt::Display for ResponseMcpCallCompletedEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
