/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RotateMcpOauthRefreshParam : Updates to an MCP credential's existing OAuth refresh configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct RotateMcpOauthRefreshParam {
    /// The replacement refresh token. Omit or pass `null` to keep the stored token. This secret is never returned in resources.
    #[serde(
        rename = "refresh_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<Option<String>>,
    /// Replacement space-separated OAuth scopes for refresh requests. Omit to keep the scopes, or pass `null` to stop sending a scope parameter.
    #[serde(
        rename = "scope",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scope: Option<Option<String>>,
    #[serde(
        rename = "token_endpoint_auth",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub token_endpoint_auth: Option<Option<Box<models::RotateMcpOauthTokenEndpointAuthParam>>>,
}

impl RotateMcpOauthRefreshParam {
    /// Updates to an MCP credential's existing OAuth refresh configuration.
    pub fn new() -> RotateMcpOauthRefreshParam {
        RotateMcpOauthRefreshParam {
            refresh_token: None,
            scope: None,
            token_endpoint_auth: None,
        }
    }
}

impl std::fmt::Display for RotateMcpOauthRefreshParam {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
