/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event")]
pub enum RunStreamEvent {
    #[serde(rename = "thread.run.created")]
    AnyOf(Box<models::RunStreamEventAnyOf>),
    #[serde(rename = "thread.run.queued")]
    AnyOf1(serde_json::Value),
    #[serde(rename = "thread.run.in_progress")]
    AnyOf2(serde_json::Value),
    #[serde(rename = "thread.run.requires_action")]
    AnyOf3(serde_json::Value),
    #[serde(rename = "thread.run.completed")]
    AnyOf4(serde_json::Value),
    #[serde(rename = "thread.run.incomplete")]
    AnyOf5(serde_json::Value),
    #[serde(rename = "thread.run.failed")]
    AnyOf6(serde_json::Value),
    #[serde(rename = "thread.run.cancelling")]
    AnyOf7(serde_json::Value),
    #[serde(rename = "thread.run.cancelled")]
    AnyOf8(serde_json::Value),
    #[serde(rename = "thread.run.expired")]
    AnyOf9(serde_json::Value),
}

