/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SafetyAlertErrorType {
    #[serde(rename = "potentially_unintended_data_transfer")]
    PotentiallyUnintendedDataTransfer,
    #[serde(rename = "potentially_unintended_data_access")]
    PotentiallyUnintendedDataAccess,
    #[serde(rename = "potentially_unintended_destructive_activity")]
    PotentiallyUnintendedDestructiveActivity,
    #[serde(rename = "other")]
    Other,
}

impl std::fmt::Display for SafetyAlertErrorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PotentiallyUnintendedDataTransfer => {
                write!(f, "potentially_unintended_data_transfer")
            }
            Self::PotentiallyUnintendedDataAccess => {
                write!(f, "potentially_unintended_data_access")
            }
            Self::PotentiallyUnintendedDestructiveActivity => {
                write!(f, "potentially_unintended_destructive_activity")
            }
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for SafetyAlertErrorType {
    fn default() -> SafetyAlertErrorType {
        Self::PotentiallyUnintendedDataTransfer
    }
}
