/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceTierParam : The service tier used for model requests.
/// The service tier used for model requests.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceTierParam {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "flex")]
    Flex,
    #[serde(rename = "priority")]
    Priority,
    #[serde(rename = "fast")]
    Fast,
}

impl std::fmt::Display for ServiceTierParam {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Auto => write!(f, "auto"),
            Self::Default => write!(f, "default"),
            Self::Flex => write!(f, "flex"),
            Self::Priority => write!(f, "priority"),
            Self::Fast => write!(f, "fast"),
        }
    }
}

impl Default for ServiceTierParam {
    fn default() -> ServiceTierParam {
        Self::Auto
    }
}
