/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionEventAgentSessionIdle : Emitted when a session becomes idle.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct SessionEventAgentSessionIdle {
    /// The type of the object. Always `agent.session.idle`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The unique ID of the event.
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "session")]
    pub session: models::SessionResource,
}

impl SessionEventAgentSessionIdle {
    /// Emitted when a session becomes idle.
    pub fn new(
        r#type: Type,
        event_id: String,
        session: models::SessionResource,
    ) -> SessionEventAgentSessionIdle {
        SessionEventAgentSessionIdle {
            r#type,
            event_id,
            session,
        }
    }
}
/// The type of the object. Always `agent.session.idle`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "agent.session.idle")]
    AgentSessionIdle,
}

impl Default for Type {
    fn default() -> Type {
        Self::AgentSessionIdle
    }
}

impl std::fmt::Display for SessionEventAgentSessionIdle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
