/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionRequiredActionResourceFunctionCall : Run a function tool and submit its result.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct SessionRequiredActionResourceFunctionCall {
    /// The type of the object. Always `function_call`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the turn that requested the function call.
    #[serde(rename = "turn_id")]
    pub turn_id: String,
    /// The ID to include when submitting the function result.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The function name.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "arguments", deserialize_with = "Option::deserialize")]
    pub arguments: Option<serde_json::Value>,
}

impl SessionRequiredActionResourceFunctionCall {
    /// Run a function tool and submit its result.
    pub fn new(
        r#type: Type,
        turn_id: String,
        call_id: String,
        name: String,
        arguments: Option<serde_json::Value>,
    ) -> SessionRequiredActionResourceFunctionCall {
        SessionRequiredActionResourceFunctionCall {
            r#type,
            turn_id,
            call_id,
            name,
            arguments,
        }
    }
}
/// The type of the object. Always `function_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "function_call")]
    FunctionCall,
}

impl Default for Type {
    fn default() -> Type {
        Self::FunctionCall
    }
}

impl std::fmt::Display for SessionRequiredActionResourceFunctionCall {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
