/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThreadResourceStatus : Current status for the thread. Defaults to `active` for newly created threads.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ThreadResourceStatus {
    ActiveStatus(Box<models::ActiveStatus>),
    LockedStatus(Box<models::LockedStatus>),
    ClosedStatus(Box<models::ClosedStatus>),
}

impl Default for ThreadResourceStatus {
    fn default() -> Self {
        Self::ActiveStatus(Default::default())
    }
}
