/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolChoiceCustom : Use this option to force the model to call a specific custom tool. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ToolChoiceCustom {
    /// For custom tool calling, the type is always `custom`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The name of the custom tool to call.
    #[serde(rename = "name")]
    pub name: String,
}

impl ToolChoiceCustom {
    /// Use this option to force the model to call a specific custom tool. 
    pub fn new(r#type: Type, name: String) -> ToolChoiceCustom {
        ToolChoiceCustom {
            r#type,
            name,
        }
    }
}
/// For custom tool calling, the type is always `custom`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Custom
    }
}



impl std::fmt::Display for ToolChoiceCustom {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
