/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ToolSearchExecutionType {
    #[serde(rename = "server")]
    Server,
    #[serde(rename = "client")]
    Client,
}

impl std::fmt::Display for ToolSearchExecutionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Server => write!(f, "server"),
            Self::Client => write!(f, "client"),
        }
    }
}

impl Default for ToolSearchExecutionType {
    fn default() -> ToolSearchExecutionType {
        Self::Server
    }
}
