/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ValidateGraderRequest {
    #[serde(rename = "grader")]
    pub grader: Box<models::FineTuneReinforcementMethodGrader>,
}

impl ValidateGraderRequest {
    pub fn new(grader: models::FineTuneReinforcementMethodGrader) -> ValidateGraderRequest {
        ValidateGraderRequest {
            grader: Box::new(grader),
        }
    }
}

impl std::fmt::Display for ValidateGraderRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
