/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VideoModel {
    #[serde(rename = "sora-2")]
    Sora2,
    #[serde(rename = "sora-2-pro")]
    Sora2Pro,
    #[serde(rename = "sora-2-2025-10-06")]
    Sora220251006,
    #[serde(rename = "sora-2-pro-2025-10-06")]
    Sora2Pro20251006,
    #[serde(rename = "sora-2-2025-12-08")]
    Sora220251208,
}

impl std::fmt::Display for VideoModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sora2 => write!(f, "sora-2"),
            Self::Sora2Pro => write!(f, "sora-2-pro"),
            Self::Sora220251006 => write!(f, "sora-2-2025-10-06"),
            Self::Sora2Pro20251006 => write!(f, "sora-2-pro-2025-10-06"),
            Self::Sora220251208 => write!(f, "sora-2-2025-12-08"),
        }
    }
}

impl Default for VideoModel {
    fn default() -> VideoModel {
        Self::Sora2
    }
}
