/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VoiceResource : A custom voice that can be used for audio output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct VoiceResource {
    /// The object type, which is always `audio.voice`.
    #[serde(rename = "object")]
    pub object: Object,
    /// The voice identifier, which can be referenced in API endpoints.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the voice.
    #[serde(rename = "name")]
    pub name: String,
    /// The Unix timestamp (in seconds) for when the voice was created.
    #[serde(rename = "created_at")]
    pub created_at: i32,
}

impl VoiceResource {
    /// A custom voice that can be used for audio output.
    pub fn new(object: Object, id: String, name: String, created_at: i32) -> VoiceResource {
        VoiceResource {
            object,
            id,
            name,
            created_at,
        }
    }
}
/// The object type, which is always `audio.voice`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "audio.voice")]
    AudioVoice,
}

impl Default for Object {
    fn default() -> Object {
        Self::AudioVoice
    }
}

impl std::fmt::Display for VoiceResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
