/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VoiceIdsOrCustomVoiceAnyOf : Custom voice reference.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct VoiceIdsOrCustomVoiceAnyOf {
    /// The custom voice ID, e.g. `voice_1234`.
    #[serde(rename = "id")]
    pub id: String,
}

impl VoiceIdsOrCustomVoiceAnyOf {
    /// Custom voice reference.
    pub fn new(id: String) -> VoiceIdsOrCustomVoiceAnyOf {
        VoiceIdsOrCustomVoiceAnyOf { id }
    }
}

impl std::fmt::Display for VoiceIdsOrCustomVoiceAnyOf {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
