/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebSearchActionResource : An action performed by the web search tool.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebSearchActionResource {
    Search(Box<models::WebSearchActionResourceSearch>),
    OpenPage(Box<models::WebSearchActionResourceOpenPage>),
    FindInPage(Box<models::WebSearchActionResourceFindInPage>),
    Other(Box<models::WebSearchActionResourceOther>),
}

impl Default for WebSearchActionResource {
    fn default() -> Self {
        Self::Search(Default::default())
    }
}
