/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookRealtimeCallIncomingData : Event data payload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct WebhookRealtimeCallIncomingData {
    /// The unique ID of this call.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// Headers from the SIP Invite.
    #[serde(rename = "sip_headers")]
    pub sip_headers: Vec<models::WebhookRealtimeCallIncomingDataSipHeadersInner>,
}

impl WebhookRealtimeCallIncomingData {
    /// Event data payload.
    pub fn new(
        call_id: String,
        sip_headers: Vec<models::WebhookRealtimeCallIncomingDataSipHeadersInner>,
    ) -> WebhookRealtimeCallIncomingData {
        WebhookRealtimeCallIncomingData {
            call_id,
            sip_headers,
        }
    }
}
