/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct WebhookEventTypeListResource {
    /// The object type, which is always list.
    #[serde(rename = "object")]
    pub object: Object,
    /// The webhook event types available to the authenticated project.
    #[serde(rename = "data")]
    pub data: Vec<String>,
}

impl WebhookEventTypeListResource {
    pub fn new(object: Object, data: Vec<String>) -> WebhookEventTypeListResource {
        WebhookEventTypeListResource { object, data }
    }
}
/// The object type, which is always list.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "list")]
    List,
}

impl Default for Object {
    fn default() -> Object {
        Self::List
    }
}

impl std::fmt::Display for WebhookEventTypeListResource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match serde_json::to_string(self) {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}
