name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, 1.82.0]  # 1.82.0 is our MSRV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
    
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
    
      - name: Build
        run: cargo build --verbose
        
      - name: Build documentation
        run: cargo doc --no-deps --all-features
        
      - name: Run tests
        run: cargo test --verbose
        
      - name: Check formatting
        if: matrix.rust == 'stable'
        run: cargo fmt --all -- --check
        
      - name: Run clippy
        if: matrix.rust == 'stable'
        run: cargo clippy --all-targets --all-features -- -D warnings
