name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: pip install pyyaml
    
    - name: Generate client
      run: |
        ./scripts/fetch_spec.sh
        ./scripts/generate.sh
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Run tests
      run: cargo test --release --verbose
    
    - name: Package
      run: cargo package --allow-dirty
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Generated OpenAI client from the latest OpenAPI specification.
          
          ## Changes
          - Updated to latest OpenAI OpenAPI spec
          - Applied Rust compatibility patches
          
          ## Installation
          Add to your `Cargo.toml`:
          ```toml
          [dependencies]
          openai-client-base = { git = "https://github.com/genai-rs/openai-client-base", tag = "${{ github.ref }}" }
          ```
        draft: false
        prerelease: false